// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBepVP3eOjxhx0fcsLeSsSh3L-fwXaDRow',
    appId: '1:704994583364:web:52d6c416714cd8fdc6ed11',
    messagingSenderId: '704994583364',
    projectId: 'cw-6-29e37',
    authDomain: 'cw-6-29e37.firebaseapp.com',
    storageBucket: 'cw-6-29e37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGkky3ajFGT-RJ3N9rBRtrpz7TwnJkAoo',
    appId: '1:704994583364:android:a0c59f8c842343c3c6ed11',
    messagingSenderId: '704994583364',
    projectId: 'cw-6-29e37',
    storageBucket: 'cw-6-29e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMw1lsikEIbQxk7SPlzDVdoO1lSm6m46g',
    appId: '1:704994583364:ios:740277f1a951ed25c6ed11',
    messagingSenderId: '704994583364',
    projectId: 'cw-6-29e37',
    storageBucket: 'cw-6-29e37.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMw1lsikEIbQxk7SPlzDVdoO1lSm6m46g',
    appId: '1:704994583364:ios:740277f1a951ed25c6ed11',
    messagingSenderId: '704994583364',
    projectId: 'cw-6-29e37',
    storageBucket: 'cw-6-29e37.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBepVP3eOjxhx0fcsLeSsSh3L-fwXaDRow',
    appId: '1:704994583364:web:f9300c8cbf968c0cc6ed11',
    messagingSenderId: '704994583364',
    projectId: 'cw-6-29e37',
    authDomain: 'cw-6-29e37.firebaseapp.com',
    storageBucket: 'cw-6-29e37.firebasestorage.app',
  );
}
